export const PATH = {
    home:"/",
    teachers:"/teachers",
    teachersAdd:"/teachers/add",
    teachersMore:"/teachers/:id",
    teachersEdit:"/teachers/:id/edit",
    students:"/students",
    studentsAdd:"/students/add",
    studentsMore:"/students/:id",
    studentsEdit:"/students/:id/edit",
    market:"/market",
    stack:"/stack",
    stackAdd:"/stack/add",
    stackEdit:"/stack/edit/:stackId",
    group:"/stack/:stackId",
    groupAdd:"/stack/:stackId/add",
    groupMore:"/stack/:stackId/:groupId",
    groupEdit:"/stack/:stackId/:groupId/edit"
}